version: "3.3"
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "16379:6379"
    restart: always
    volumes: 
      - trading_bot_redis_volume:/var/lib/redis
    networks:
      - trading_bot_network

  trading_bot_postgres:
    image: postgres:13-alpine
    container_name: trading_bot_postgres
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - postgres.env
    volumes:
      - trading_bot_postgres_volume:/var/lib/postgres
    networks:
      - trading_bot_network

  signal_service:
    build: 
      context: .
      dockerfile: docker/signalService.Dockerfile
    container_name: signal_service
    depends_on:
      - redis
      - trading_bot_postgres
    ports:
      - "5555:5555"
    restart: always
    env_file:
      - redis.env
      - signal_service.env
    networks:
      - trading_bot_network

  datastreamer_service:
    build: 
      context: .
      dockerfile: docker/datastreamer.Dockerfile
    container_name: datastreamer_service
    depends_on:
      - redis
      - trading_bot_postgres
    ports:
      - "5556:5556"
    restart: always
    env_file:
      - redis.env
      - datastreamer.env
    networks:
      - trading_bot_network

  telegram_service:
    build: 
      context: .
      dockerfile: docker/telegramService.Dockerfile
    container_name: telegram_service
    depends_on:
      - trading_bot_postgres
    ports:
      - "5557:5557"
    restart: always
    env_file:
      - telegram_service.env
    networks:
      - trading_bot_network

volumes:
  trading_bot_postgres_volume:
  trading_bot_redis_volume:

networks:
  trading_bot_network: