version: "3.3"
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "16379:6379"
    restart: always
    volumes: 
      - trading_bot_redis_volume:/var/lib/redis
    networks:
      - signal_service_network

  trading_bot_postgres:
    image: postgres:13-alpine
    container_name: trading_bot_postgres
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - postgres.env
    volumes:
      - trading_bot_postgres_volume:/var/lib/postgres
    networks:
      - signal_service_network

  signal_service:
    build: 
      context: .
      dockerfile: docker/signalService.Dockerfile
    container_name: signal_service
    depends_on:
      - redis
      - trading_bot_postgres
    ports:
      - "5555:5555"
    restart: always
    env_file:
      - redis.env
      - signal_service.env
    volumes:
      - signal_service_volume:/var/lib/signal_service
      - type: bind
        source: ./signal_service_tunnelFolder
        target: /signal_service_tunnelFolder
    networks:
      - signal_service_network

  datastreamer_service:
    build: 
      context: .
      dockerfile: docker/datastreamer.Dockerfile
    container_name: datastreamer_service
    depends_on:
      - redis
      - trading_bot_postgres
    ports:
      - "5556:5556"
    restart: always
    env_file:
      - redis.env
      - datastreamer.env
    volumes:
      - datastreamer_volume:/var/lib/datastreamer
      - type: bind
        source: ./datastreamer_service_tunnelFolder
        target: /datastreamer_service_tunnelFolder
    networks:
      - signal_service_network

volumes:
  signal_service_volume:
  datastreamer_volume:
  trading_bot_postgres_volume:
  trading_bot_redis_volume:

networks:
  signal_service_network: