name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dotnet-coverage
      shell: powershell
      run: |
        dotnet tool install --global dotnet-coverage
        
    - name: Restore dependencies
      run: dotnet restore TradingBot.sln

    - name: Build
      run: dotnet build --no-restore TradingBot.sln

    - name: Test and collect
      shell: powershell
      run: |
       dotnet-coverage collect 'dotnet test --no-build --logger trx TradingBot.sln' -f xml -o 'coverage.xml'

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
